### ISSUE TITLE
geo_near throwing error

### ISSUE THREAD

**Issue by dhruvasagar** [kristianmandrup/mongoid-geo#38] opened 2011-06-03 03:46 UTC
Hi when I do this :

Person.geo_near([45, -3], :pos)

I get this :

ruby-1.9.2-p180 :031 > Person.geoNear([45, -3, 10], :pos)
NoMethodError: undefined method `from_point=' for #<Person:0x000000023a0938>
    from /home/dhruva/.rvm/gems/ruby-1.9.2-p180/gems/mongoid-2.0.2/lib/mongoid/attributes.rb:162:in`method_missing'
    from /home/dhruva/.rvm/gems/ruby-1.9.2-p180/gems/mongoid_geo-0.6.1/lib/mongoid/geo/near.rb:71:in `block in query_result'
    from /home/dhruva/.rvm/gems/ruby-1.9.2-p180/gems/mongoid_geo-0.6.1/lib/mongoid/geo/near.rb:67:in`map'
    from /home/dhruva/.rvm/gems/ruby-1.9.2-p180/gems/mongoid_geo-0.6.1/lib/mongoid/geo/near.rb:67:in `query_result'
    from /home/dhruva/.rvm/gems/ruby-1.9.2-p180/gems/mongoid_geo-0.6.1/lib/mongoid/geo/near.rb:34:in`geoNear'
    from (irb):31
    from /home/dhruva/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/commands/console.rb:44:in `start'
    from /home/dhruva/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/commands/console.rb:8:in`start'
    from /home/dhruva/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/commands.rb:23:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'

**Comment by dhruvasagar** [comment] 2011-06-03 03:47
This is my model :

class Person
  include Mongoid::Document
  extend Mongoid::Geo::Near

  field :location, :type => Array, :geo => true

  geo_index :location
end

**Comment by ryanong** [comment] 2011-06-03 06:02
0.6.1 isn't stable yet. Not sure why @kristianmandrup pushed release.

@kristianmandrup you really should run specs before releasing. Everything is basically broken I am on a path to fixing and completely changing everything we will definitely want to re band this 0.7 or even 1.0 as there are HUGE api changes.

**Comment by dhruvasagar** [comment] 2011-06-03 06:43
Cool, how can I contribute ? I assume you'd want me to create a fork, fix,
test and then send you a pull request ?

On Fri, Jun 3, 2011 at 11:32, ryanong <
reply@reply.github.com>wrote:

> 0.6.1 isn't stable yet. Not sure why @kristianmandrup pushed release.
> 
> @kristianmandrup you really should run specs before releasing. Everything
> is basically broken I am on a path to fixing and completely changing
> everything we will definitely want to re band this 0.7 or even 1.0 as there
> are HUGE api changes.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kristianmandrup/mongoid-geo/issues/38#comment_1289977

## 

Thanks & Regards,

## Dhruva Sagar http://dhruvasagar.net

Technical Developer - Mentor,
Artha42 Innovations Pvt. Ltd. http://www.artha42.com/

Become an expert in Rails. Join our 3 day Rails workshop and learn Ruby,
Rails 3, Cucumber and Git.
http://www.railspundit.com

**Comment by kristianmandrup** [comment] 2011-06-03 08:42
Sorry guys, I have been working on other things lately. I merged @salbitos changes (commit 30660eb17) without much thought and then added support for using GeoPoints and GeoVectors. The fields tests ran ok, but I wasn't sure about @salbito's major bug fix/change of reversing to using (lng, lat) instead of the old default (lat, lng). This makes perfect sense if using mongo > 1.6 I think and should thus be the default.

However (lng. lat) only would then not work for users of mongo < 1.7 I think? 
This is why I used to have a global config to set the mongo version used and allow for a :spherical mode setting. I'm not sure where this is going or should be going... For now I think there should still be backwards compatibility somehow.

I should set off some time this weekend to look more into it and see what @ryanong is doing. We should target a 1.0 release and have it stuffed with API documentation using Yard IMO. I just used Yard on my _troles_ (roles) project I've been working on with great success. 

Thanks for the patience and please help out so we can get the 1.0 release soon. 
Yeah, Fork it, Fix it and _don't_ Forget (to run the specs). I'm really sorry I made such a bad release!
Enjoy the weekend and happy coding!

Kris

**Comment by kristianmandrup** [comment] 2011-06-03 10:27
Successfully yanked gem: mongoid_geo (0.6.1)

**Comment by ryanong** [comment] 2011-06-03 14:43
I am actually thinking of moving a lot of the code over to criteria and make it a function like find.
This would allow for chaining. The only reason to include mongoid:geo:near in a model would be for a few extentions that involve calculating distances, and simplifying long-lat associations and a few other things.

Also closing because you yanked the gem.

**Closed as completed by ryanong** 2011-06-03 14:43 UTC

**Comment by salbito** [comment] 2011-06-03 14:50
Hey sorry about this but I did not realize that we would be pushing out this gem immediately. Also I realize that I may not have been clear enough in the changes made. I will change the docs as soon as possible. The issue is this. If you had used mongoid_geo at any point prior to my change you have since been storing your coordinates at [lat, lng] which is incorrect storage on mongodb. The change i made did flip it so that all input going through mongoid_geo would set the array as [lng, lat]. Now the problem is that if you previously have been storing data as [lat, lng] you would pretty much have to go through all your geo data and flip the array. Now many of the geo calculations are done on mongodb. Not within mongoid_geo. So for those storing it as [lat, lng], they have always been getting incorrect query results as the form for shapes as projected on a spherical form were incorrect. This gem is not really ready for release and the unfortunate part is that there is alot of cleanup to do and some uniformity to be dealt with all the committers on this project. I believe we should have a refactor branch that all comitters should be putting their efforts towards. I have a major refactor branch that should be the base of the rebuild of mongoid_geo. My changes also did not affect querying as it only flipped the way data was stored...not how it was used in calculations that for the most part mongoid_geo has no hold on because its dealt with on the mongodb server side.

**Comment by salbito** [comment] 2011-06-03 14:51
Also I have stated this before. This was being testing by me on all ruby versions but some comitters have only been testing them on 1.9.2 which leads to many problems. One being that they are calling functions only available in 1.9.2 Please test in all versions.

**Comment by kristianmandrup** [comment] 2011-06-03 15:11
@salbito I agree with all your points. Let's all work towards a beautiful, slim 1.0 release that is nice, tidy and documented.
We should target such a release for the end of this month (June) at the latest. I will look at @ryanong's branch next week and go from there...
No more hacky-t-hack and quick releases from me ;) I will start my own refactor branch next week and pull in from you guys and discuss implementation details etc. Skype or sth. My id: _mainster-dk_

There are currently certain methods such as #lat and #lng that now return incorrect results due to the lat/lng flip.
I am happy there is no need to support both "modes", as I had previously assumed. My bad!

The specs also need a major rewrite, using example groups: http://blog.davidchelimsky.net/2010/11/07/specifying-mixins-with-shared-example-groups-in-rspec-2/

The gem should also be designed for use with _geo_calc_ IMO, as the _GeoPoint_ functionality makes it much easier to work with points than passing arrays around in a specific format. This also allows for the use of _GeoVectors_ and other goodies to come.... 
 In the future I will make sureto test on other version of ruby before a release. 
Is there a good gem for that, or I just have to install and test it using different rvm profiles? 
Thanks!  

Kristian

**Comment by salbito** [comment] 2011-06-10 15:29
@kristianmandrup @ryanong

I have my refactor branch on my fork of the project. All the specs previous have been taken out and the gem has a new structure. I think we need to start from no specs and then build them backup. Only in trying to create tests and i figuring out the point of some of the code. Lets keep it concise. I'm looking at @ryanong's branch and will merge in what has into mine.

**Comment by kristianmandrup** [comment] 2011-06-10 19:42
@salbito please check out my 1_0_beta branch. I also made a new structure and started redesigning all the specs. Let's see how we can combine our efforts the best way. My readme contains an overview of what I've done and my ideas. Have a nice weekend! I sincerely appreciate your determination to get this working and done :)

**Comment by salbito** [comment] 2011-06-11 20:47
I'm currently moving to a new apartment this weekend. I'll try to get to it when I can.

**Comment by kristianmandrup** [comment] 2011-06-11 22:49
I understand. Just to let you know, I've come pretty far with the new design, specs and all... shaping up pretty good!
Good luck moving in ;)
